version: "3.8"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    environment:
      - MARIADB_ROOT_PASSWORD=MARIApwd1234!YES
      - MARIADB_DATABASE=glpidb
      - MARIADB_USER=glpi_user
      - MARIADB_PASSWORD=GLPIopenMe1234!
    volumes:
      - /data/docker/glpi/mariadb:/var/lib/mysql
    networks:
      - glpi
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.hostname == docker02

#GLPI Container
  glpi:
    image: diouxx/glpi
    #container_name : glpi
    #hostname: glpi
    #ports:
    #  - "80:80"
    #restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /data/docker/glpi/html:/var/www/html/glpi
    environment:
      - TIMEZONE=Europe/Brussels
      #- VERSION_GLPI=9.5.6
    networks:
      - glpi
      - npm
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.hostname == docker02

networks:
  glpi: {}
  npm:
    external: true